# Generated by Django 4.2.6 on 2023-12-26 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.kategori')),
            ],
        ),
    ]
