# Generated by Django 4.2.6 on 2023-12-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('belum_selesai', 'Belum Selesai'), ('Selesai', 'selesai')], default='Belum Selesai', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tanggal_jatuh_tempo',
            field=models.DateTimeField(),
        ),
    ]
